#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export VARIANT="v0.portal5h-webrtc-bitrate-quality"
export EXPECTED_VERSION_CODE="23"
export EXPECTED_VERSION_NAME="0.6.6"
export EXPECTED_NATIVE_SYSTEM_WEBRTC_LIBS="1"
export EXPECTED_PORTAL_VARIANT_MARKER="v0.portal5h-webrtc-bitrate-quality"
export EXPECTED_SOFTWARE_BITMAP_FRAME_PUMP="0"
export EXPECTED_BITMAP_COPY_FRAME_PUMP="1"
export EXPECTED_WEBRTC_SESSION_CONTROL="1"
export EXPECTED_WEBRTC_INPUT_CHANNEL="1"
export EXPECTED_WEBRTC_TOUCH_OVERLAY="1"
export EXPECTED_WEBRTC_QUALITY_TUNE="1"
export EXPECTED_WEBRTC_QUALITY_REASON_MARKER="portal5h_default_webrtc_ui_and_explicit_h264_bitrate"
export EXPECTED_WEBRTC_BITRATE_TUNE="1"
export EXPECTED_WEBRTC_DEFAULT_UI="1"
export OFFLINE_RESULT_NAME="PASS_OFFLINE_IMAGE_V0PORTAL5H_WEBRTC_BITRATE_QUALITY"
export READ_ONLY_RESULT_NAME="PASS_READ_ONLY_V0PORTAL5H_WEBRTC_BITRATE_QUALITY"

exec "${ROOT_DIR}/tools/r2-verify-v0.portal5a-native-webrtc-runtime.sh" "$@"
