#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export VARIANT="v0.portal5j-projection-texture-probe"
export EXPECTED_VERSION_CODE="25"
export EXPECTED_VERSION_NAME="0.6.8"
export EXPECTED_NATIVE_SYSTEM_WEBRTC_LIBS="1"
export EXPECTED_PORTAL_VARIANT_MARKER="v0.portal5j-projection-texture-probe"
export EXPECTED_SOFTWARE_BITMAP_FRAME_PUMP="0"
export EXPECTED_BITMAP_COPY_FRAME_PUMP="1"
export EXPECTED_WEBRTC_SESSION_CONTROL="1"
export EXPECTED_WEBRTC_INPUT_CHANNEL="1"
export EXPECTED_WEBRTC_TOUCH_OVERLAY="1"
export EXPECTED_WEBRTC_QUALITY_TUNE="1"
export EXPECTED_WEBRTC_QUALITY_REASON_MARKER="portal5j_projection_texture_zero_copy_probe_1080p60"
export EXPECTED_WEBRTC_BITRATE_TUNE="1"
export EXPECTED_WEBRTC_DEFAULT_UI="1"
export EXPECTED_WEBRTC_RUNTIME_TUNING="1"
export EXPECTED_WEBRTC_RUNTIME_REASON_MARKER="portal5j_projection_texture_zero_copy_probe_1080p60"
export EXPECTED_WEBRTC_RUNTIME_MAX_FPS="60"
export EXPECTED_WEBRTC_CAPTURE_PROBE="1"
export EXPECTED_MANAGE_MEDIA_PROJECTION="1"
export OFFLINE_RESULT_NAME="PASS_OFFLINE_IMAGE_V0PORTAL5J_PROJECTION_TEXTURE_PROBE"
export READ_ONLY_RESULT_NAME="PASS_READ_ONLY_V0PORTAL5J_PROJECTION_TEXTURE_PROBE"

exec "${ROOT_DIR}/tools/r2-verify-v0.portal5a-native-webrtc-runtime.sh" "$@"
